### ISSUE TITLE
[Feature Request] Some simple Markdown parsing

### ISSUE THREAD

**Issue by kehphin** [MaxLap/standard-notes-indent-editor#1]
Heya, stumbled upon your editor and it's rockin'! The default editor's text wrap not respecting indents annoyed me to no end. Just had a couple wishes regarding parsing some markdown features:

1. `text snippets`,

```
2. code blocks
```

3. Some rough heading parsing (#, ##, ###, etc), such as bolding the letters. Size differences for the headings would be even better!

If I have some time, I can take a shot at it too! Thanks again for this editor.

**Comment by MaxLap** [comment]
Hello, I agree that those would all be useful features. 

1. `text snippets` are pretty straight forward.

2. Code blocks feel a little more tricky to get right display-wise. Since the editor doesn't hide characters, the ``` need to appear somewhere and still be in the flow of the text. I will play with it and see if I can get a feel I like.

3. I agree that some form of heading is required. I'm not sure how I want to do it as I'm often annoyed by their massive sizes/margin in other tools and always end up with ### to make them a reasonable size.

**Comment by MaxLap** [comment]
I just released a version of the editor with all 3 features. 
The code block is not as nice as I'd like, but it's better than nothing. I'll surely improve it later on, when I've used it a little.

The editor now also highlights urls and you can ctrl+click them to open them.

The demo explain is all https://maxlap.github.io/standard-notes-indent-editor/demo.html
