### ISSUE TITLE
Ajouter licence

### ISSUE THREAD

**Issue by gabrielcossette** [MaxLap/standard-notes-indent-editor#10]
Bonjour!

L'extension semble géniale :)

Est-ce qu'une licence libre pourrait être assignée au code svp?

Merci!

**Comment by MaxLap** [comment]
Bonjour, 

C'est un choix que j'ai fait de ne pas en mettre pour l'instant. Je me questionne sur ce que je veux faire avec ce projet et s'il pourrait devenir une part d'un projet payant.

Tu peux quand même utiliser l'extension

**Comment by MaxLap** [comment]
Bonjour, il y a maintenant une license sur le projet: AGPL.

Le projet que j'ai utilisé comme base n'avait pas de license, il en a maintenant une alors je ne peux qu'utiliser la même.

Cordialement
