### ISSUE TITLE
Support for ordered lists

### ISSUE THREAD

**Issue by shompoe** [MaxLap/standard-notes-indent-editor#11]
This editor is fantastic.

Have you considered adding supprt for ordered lists?

So starting a line with "1. " the editor would use the same indenting and line spacing as with un-ordered lists and when you start a new line it would automatically type "2. " at the start. Then, if you were to insert or delete an item the rest of the items would re-number themselves automatically.

**Comment by MaxLap** [comment]
Hello, I'm glad you like it. 

The automatic insertion of a new number could work, if previous indentation is number-based, then pressing enter enter inserts with the correct number. I could be comfortable with such a feature.

However, the automatic fixing based on inserts/removal I am not comfortable with, not automatically. A shortcut that would trigger the fixing of the numbers could be acceptable.

I have not needed such a feature up to now. I will keep it in mind and see if it could be useful to me.

**Comment by MaxLap** [comment]
Hello, the latest version of Indent editor now has numbered list functionality. Both for the indentation aspect, and for the auto-increment when pressing inter (for the new line only).
