### ISSUE TITLE
Line wrapping bug

### ISSUE THREAD

**Issue by jian-x-li** [MaxLap/standard-notes-indent-editor#15]
On display of 1920 x 1080, some lines are wrapped half-way of the screen (leaving the right-half of the screen blank), some wrapped to the end of the screen (the ideal setting). For example, copy and paste the article text of https://religion.blogs.cnn.com/2012/06/01/survey-nearly-half-of-americans-subscribe-to-creationist-view-of-human-origins/ into a note, you will notice the bug.
Can the line wrapping be the same as that of the default editor?

**Comment by MaxLap** [comment]
Hello,

If a line doesn't reach the width of the display, it will not wrap at a shorter width. This is the intended behavior. I admit it is not quite ideal for a full text like this, but when dealing with mostly single lines, which are sometimes long (such as for todos and quick notes), i feel the current behavior is better.

I limit the size that a line can be when it wraps to make things easier to read. A paragraph that is too wide is, i feel, harder to read, and a line that wraps for a single word is annoying. Doing it the current way means that if there is wrapping, then there will be a good part of the line that will be wrapped.

I'm not aware of a way to configure editors in Standard notes, or of a way that custom editors can hook into. Sorry
