### ISSUE TITLE
Feature Request: Monospaced Font

### ISSUE THREAD

**Issue by MustachedMario** [MaxLap/standard-notes-indent-editor#17]
I think, formating plaintext with a monospaced font is alot easier.
Currently, i add tripple ''' to the text, to format some parts of it, but this is not comfortable as it could.

So please add a way to respect the global sn monofont switch.
Thanks.

**Comment by MaxLap** [comment]
I wish I could, but SN gives me no way of getting that information, so I can't.

**Comment by MaxLap** [comment]
Hello, I added a config panel to IndentEditor. A button appears in the top-right you can use to choose to have monospace font.

The actually used font is the one coming from the theme.
