### ISSUE TITLE
new config doesn't work well with dark theme

### ISSUE THREAD

**Issue by 17prime** [MaxLap/standard-notes-indent-editor#18]
Just a note to point out that the new config page appears with dark text on a dark background when using a dark theme (just testing with Slate Theme on Desktop 3.4.1), requiring one to turn off the theme to read it.

**Comment by MaxLap** [comment]
Thank you, I didn't think of that at all. I will look into it.

**Comment by MaxLap** [comment]
Fixed in the latest version. Thank again for the report
