### ISSUE TITLE
Press return twice to end a list

### ISSUE THREAD

**Issue by frego** [MaxLap/standard-notes-indent-editor#20]
Hi,

Great editor, I love it. It is slowly becoming my editor of choice.

When making a list, pressing return creates a bullet point. What do you think if pressing return directly again, deletes the current empty bullet point and creates a new line.

At the moment, to exit a list, you need to press return, then press backspace twice to delete the empty bullet point and then press return again.

Cheers,

**Comment by MaxLap** [comment]
Hello, glad you like the editor!

You can press "Shift-Enter" to create a new line without any kind of indentation (and without bullet points).
