### ISSUE TITLE
Marking text as title using # not working

### ISSUE THREAD

**Issue by jrabensc** [MaxLap/standard-notes-indent-editor#3]
Just tried out this editor and everything is working perfectly except the title feature you described in the readme: 

> Lines starting with a number sign (#) are headers, shown as bold and bigger text.

![image](https://user-images.githubusercontent.com/6616405/72971590-4182ca00-3dca-11ea-9204-141ed20e9dca.png)

I expected those lines starting with # to be bold. Is this correct?

**Comment by MaxLap** [comment]
It should be working. I wonder if your app is, for some reason, still on the older version of the extension. Could you try uninstalling and reinstalling the extension, maybe that will force the update.

**Comment by jrabensc** [comment]
Thanks, this solved it.
