### ISSUE TITLE
Add Spell Check

### ISSUE THREAD

**Issue by christianhans** [MaxLap/standard-notes-indent-editor#5]
Not sure how feasible with Code Mirror. Would be still nice to have Spell Check eventually.

**Comment by MaxLap** [comment]
Sadly, at the moment, it doesn't seem possible to make CodeMirror use the browser's spell checker. CodeMirror is being rewritten, so maybe in the future it will be possible.

The code as it is heavily relies on how CodeMirror works. So switching would mean redoing everything with a different base editor, and it's not clear how much code would be reusable.

A rewrite is unlikely unless there is a something I feel that I need and cannot achieve with CodeMirror. Spellcheck is not something I personally need, I didn't even consider the possibility of it until someone else mentionned it to me in SN's Slack.
