### ISSUE TITLE
Add in-editor search via CTRL/CMD+F

### ISSUE THREAD

**Issue by christianhans** [MaxLap/standard-notes-indent-editor#7]
Similar to Minimal Markdown Editor

**Comment by MaxLap** [comment]
Did you try? This editor was started from Minimal Markdown Editor. I do not have access to a Mac to test, but on my PC using FireFox, both CTRL+F and ALT+F open the in-editor search.

**Comment by christianhans** [comment]
Ah yes, it is there and seems to work flawlessly. Not sure why it didn't seem to work the first time!
