### ISSUE TITLE
Increase Bottom Margins for Headings

### ISSUE THREAD

**Issue by christianhans** [MaxLap/standard-notes-indent-editor#8]
Currently the bottom margin between headings and paragraphs is very narrow.

<img width="594" alt="Screen Shot 2020-02-05 at 9 31 48 AM" src="https://user-images.githubusercontent.com/355541/73850807-70516500-47fa-11ea-8507-0e7e530e956b.png">

**Comment by MaxLap** [comment]
One of the goal of the editor is for the plain text to look pretty similar to the transformed version. The way I see it, if I want spacing in the highlighted edition, I probably also want it in the raw plain text one too. So I use a newline to make that spacing.

Hopefully that isn't too much of an issue for you.
